spring:
  docker:
    compose:
      file:
        - ../infra/compose.dev.yaml
      profiles:
        active:
          - obs

management:
  endpoints:
    web:
      exposure:
        include: "*"

  opentelemetry:
    enabled: true
    logging:
      export:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_LOGS_ENDPOINT:http://localhost:9041/v1/logs}

    tracing:
      export:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:http://localhost:9041/v1/traces}

  otlp:
    metrics:
      export:
        enabled: true
        url: ${OTEL_EXPORTER_OTLP_METRICS_ENDPOINT:http://localhost:9041/v1/metrics}
