spring:
  main:
    banner-mode: off

  docker:
    compose:
      enabled: true
      file: ../infra/compose.be-dev.yaml

  datasource:
    url: jdbc:postgresql://localhost:9010/dokja
    username: dokja
    password: dokja

  data:
    redis:
      host: localhost
      port: 9020

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000/realms/dokja-dev

app:
  storage:
    s3:
      endpoint: http://localhost:9030
      region: vi
      access-key: dokja
      secret-key: dokja

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
