spring:
  main:
    banner-mode: off

  docker:
    compose:
      enabled: true
      file: docker-compose.yaml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9002/realms/dokja-dev

  autoconfigure:
    exclude:
      - org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
      - org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration
      - org.springframework.boot.flyway.autoconfigure.FlywayAutoConfiguration
