name: Build
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  backend-build:
    uses: tozydev/gh-actions/.github/workflows/shared-gradle-build.yml@v1
    with:
      # language=bash
      build-script: |
        cd backend
        chmod +x ./gradlew
        ./gradlew :api:build --stacktrace
    secrets:
      github-token: ${{ github.token }}

  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup vite plus
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: 24
          cache: true
          run-install: false

      - name: Install dependencies
        working-directory: frontend
        run: vp install

      - name: Check
        working-directory: frontend
        run: vp check

      - name: Build
        working-directory: frontend
        run: vp run -r build
